### ISSUE TITLE
Call OPC UA Methods with Array Input parameters

### ISSUE THREAD

**Issue by eoursel** [BiancoRoyal/node-red-contrib-iiot-opcua#1]
Hi, 

I am trying to call a method on the Global Discovery Server just published by OPC Foundation. The trouble is that the Method-Caller node does not allow to enter parameters which are an array of strings. Most OPC UA methods of the Global Discovery Server use a parameter ServerCapabilities which is a StringList. 

I understood it could inject a message instead of using the wizard but i am not sure how to define the syntax of the message. 

Thanks

**Comment by biancode** [comment]
Hi Eric,

please try the new v1.2.0 with more options to send parameters via msg object
and I'll test more with such methods.

example for bark method is now:

`[{"id":"9f1dab9d.97fac","type":"tab","label":"IIoT OPC UA Method Call","disabled":false,"info":""},{"id":"16840277.94e98e","type":"debug","z":"9f1dab9d.97fac","name":"","active":true,"console":"false","complete":"true","x":790,"y":100,"wires":[]},{"id":"1dacbf1b.0b3f01","type":"OPCUA-IIoT-Method-Caller","z":"9f1dab9d.97fac","connector":"82f5412f.6564f8","objectId":"ns=4;i=1234","methodId":"ns=4;i=12345","value":"","name":"","inputArguments":[{"name":"barks","dataType":"UInt32","value":"3"},{"name":"volume","dataType":"UInt32","value":"6"}],"x":620,"y":140,"wires":[["16840277.94e98e","23c467db.f4287"]]},{"id":"23c467db.f4287","type":"OPCUA-IIoT-Response","z":"9f1dab9d.97fac","name":"","showStatusActivities":false,"showErrors":false,"x":800,"y":140,"wires":[["83f9aeba.fb88a"]]},{"id":"83f9aeba.fb88a","type":"debug","z":"9f1dab9d.97fac","name":"","active":false,"console":"false","complete":"true","x":940,"y":140,"wires":[]},{"id":"7b860fbc.baba08","type":"OPCUA-IIoT-Inject","z":"9f1dab9d.97fac","injectType":"inject","payload":"","payloadType":"date","topic":"","repeat":"","crontab":"","once":false,"startDelay":"","name":"","addressSpaceItems":[],"x":140,"y":140,"wires":[["1dacbf1b.0b3f01"]]},{"id":"5c0eb880.ae3358","type":"inject","z":"9f1dab9d.97fac","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":140,"y":200,"wires":[["e3999294.0851b"]]},{"id":"e3999294.0851b","type":"function","z":"9f1dab9d.97fac","name":"bark six time with volume twelve","func":"msg.payload = {\n    objectId: 'ns=4;i=1234',\n    methodId: 'ns=4;i=12345',\n    inputArguments: [\n        {name: 'barks', dataType:'UInt32', value:'6'},\n        {name: 'volume', dataType:'UInt32', value:'12'}\n    ],\n    methodType: 'basic'\n}\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":200,"wires":[["1dacbf1b.0b3f01"]]},{"id":"94a2cfac.db9368","type":"comment","z":"9f1dab9d.97fac","name":"Information","info":"If you have none OPC UA server on other tabs, \nplease drag&drop an OPC UA Server \nfrom the package nodes on this tab!","x":130,"y":80,"wires":[]},{"id":"82f5412f.6564f8","type":"OPCUA-IIoT-Connector","z":"","endpoint":"opc.tcp://localhost:55388/UA/NodeREDIIOTServer","keepSessionAlive":true,"loginEnabled":false,"securityPolicy":"None","securityMode":"NONE","name":"Method Server","showStatusActivities":false,"showErrors":false}]`

cya
Klaus

**Comment by biancode** [comment]
reopen if it does not fit your needs
