### ISSUE TITLE
No datapoint info inside a subscribed event

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#10]
Hi Klaus,

I am testing an injector with two data points connected to a listener that itself is connected to an OPC/UA server. After the injector is started I see two subscribed data points. So far so good.

If I trigger a change of value I get the following data structure:

`{"value":{"dataType":"Boolean","arrayType":"Scalar","value":false},"statusCode":{"value":0,"description":"No Error","name":"Good"},"sourceTimestamp":"2018-02-22T14:58:11.260Z","sourcePicoseconds":0,"serverTimestamp":"2018-02-22T14:58:11.721Z","serverPicoseconds":0}`

My goal is to use your multi node capability to reduce the amount of flows to be created.

What I need is the corresponding data point, description that triggered this event.

How can I get this info bound to the event? 

... and what is meta inject, multi node option means for the listener node?

**Comment by biancode** [comment]
Hi Giovanni,

did you check the msg object?

![image](https://user-images.githubusercontent.com/4369867/36549821-08382c66-17f4-11e8-90ae-b4f88abc45e9.png)

**Comment by biancode** [comment]
and you get a message per monitored object / nodeId

**Comment by biancode** [comment]
and the result filter could pick up what you are searching for ...

![image](https://user-images.githubusercontent.com/4369867/36550336-54ae47c8-17f5-11e8-89b9-7f648bd39be3.png)

**Comment by biancode** [comment]
The Meta Inject was an idea to take care about sending some meta data to react (read, write ...) on events, but I found no time to finish that. It is inactive for now.

**Comment by chminngi** [comment]
I cannot see the payload mentioned before

<img width="934" alt="image" src="https://user-images.githubusercontent.com/15190791/36563458-6dbe6f70-181a-11e8-87ec-9e0bf59c74c0.png">

**Comment by biancode** [comment]
Switch the debug node to msg and not just msg.payload ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
