### ISSUE TITLE
NodeJS 12 - not compatible

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-iiot-opcua#106]
**I'm submitting a ...**  (check one with "x")
   
## Feature
 - (X ) feature request
 
 **What is the motivation or Use Case for your feature request?**
 
 
 
     
* **Node-RED version:** 
v1.x

* **node-red-contrib-iiot-opcua version:** ``

* **Node:** (min. 8.x)
   `node --version` = 12.x

**Comment by biancode** [comment]
I stopped contributing to Node-RED for now. I have to write my master thesis first.

**Comment by biancode** [comment]
Sponsors and interested collaborators are welcome https://contact.bianco-royal.com/

**Comment by biancode** [comment]
Node-RED v1.x with v3.11.1+

**Comment by Tom-Simon** [comment]
Hello,

is this still the case? I've recently updated to NodeJS 12.4.1 and Node-Red 1.0.3 and can use your great opc ua nodes without any new problems?

**Comment by biancode** [comment]
@Tom-Simon, for now, I just tested with Nodejs 10
