### ISSUE TITLE
Nodes not all appearing in the node-red

### ISSUE THREAD

**Issue by Sibonelo10** [BiancoRoyal/node-red-contrib-iiot-opcua#110]
**I'm submitting a ...**  (check one with "x")
   
## Feature
 - ( ) feature request
 
 **What is the motivation or Use Case for your feature request?**
 
 
 

## Support
 - support request => **Please do not submit support requests here**, instead see use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer)
 - ( ) simple question => please visit the Wiki and Info tab by clicking on the node inside Node-RED before
 - FAQ: Can I send you individual support requests via E-Mail? 
   - Yes, sure! :-D
   
   
   

## Problem
 - ( ) bug report => please search GitHub for a similar issue or PR before submitting
 - ( ) unexpected behaviour => please visit the Wiki before

### Information
 **Current behaviour**
 
 
 **Expected behaviour**
 
 
 **Minimal reproduction of the problem with instructions**
 
   1. 
   2. 
   3. 
   

#### Your Environment
**Please tell us about your environment:**

  * ( ) I am using just the Node-RED package and got node-opcua installed with it
  * ( ) I have installed node-opcua global from source (using git clone)
  * ( ) I have installed node-opcua as a global package (using npm i -g) 
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting OPC UA system:
   
     - Name   :
     - Version:
     - Vendor :
     - Link   : https://
     
* **Node-RED version:** 

* **node-red-contrib-iiot-opcua version:** ``

* **Node:** (min. 8.x)
   `node --version` =

**Comment by biancode** [comment]
please, fill out the template and reopen - min versions and system info
