### ISSUE TITLE
Injecting 0 to some DataTypes is not working for Demo Server

### ISSUE THREAD

**Issue by prrw** [BiancoRoyal/node-red-contrib-iiot-opcua#113]
## Problem
 - (x) bug report => Injecting 0 for any integer node is not working

### Information
 **Current behaviour**
 
In the standard example "**_IIoT OPC UA ASO Types_**", if we inject 0 to UInt64, Int64, Int32, Int16, Double or Float, it does not work.

- Int16 and Int32 throw an error: ```Error: Expecting a number```
- Int64 and UInt64 throw an error. ```Error: Error```
- Double or Float do not throw any error but it writes 'nan' to the server
 
#### Your Environment
**Please tell us about your environment:**

  * ( ) I am using just the Node-RED package and got node-opcua installed with it
  * ( ) I have installed node-opcua global from source (using git clone)
  * (x) I have installed node-opcua as a global package (using npm i -g) 
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - (x) Windows: Windows 10 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
* **Node-RED version:**  `0.20.8`

* **node-red-contrib-iiot-opcua version:** `3.10.2`

* **Node:** (min. 8.x)
   `node --version` = `10.16.3`

**Comment by biancode** [comment]
Hi, provide an example flow, please!

**Comment by prrw** [comment]
[flows.zip](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/3627048/flows.zip)
![grafik](https://user-images.githubusercontent.com/40856484/65159672-bddc5980-da34-11e9-8146-2df9b49e1184.png)

**Comment by biancode** [comment]
working with v5.2.0
![image](https://user-images.githubusercontent.com/4369867/70850317-29459400-1e89-11ea-831f-1f9419568e88.png)
![image](https://user-images.githubusercontent.com/4369867/70850326-4aa68000-1e89-11ea-82dd-9c53c7e2dd81.png)

**Comment by biancode** [comment]
UInt64 does not work anymore

**Comment by biancode** [comment]
Double gets nan on 0.0 init

**Comment by biancode** [comment]
convert must do a Number() wrap for node-opcua 0.7.4
![image](https://user-images.githubusercontent.com/4369867/70851161-2602d600-1e92-11ea-95c6-064164ea8a92.png)

**Comment by biancode** [comment]
Example flow needs 3.11.2 or above
[ZeroASOFlowExample.json.zip](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/3964013/ZeroASOFlowExample.json.zip)
