### ISSUE TITLE
facing issue while writing node in opcua server as well as in url discovery 

### ISSUE THREAD

**Issue by akshays3** [BiancoRoyal/node-red-contrib-iiot-opcua#114]
Facing below  Issue while write node and read in iiot-opcua 

 .... ( 1137)
RegisterServer to the LDS  has failed during secure connection  => please check that you server certificate is trusted by the LDS err:_socket has been disconnected by third party
contacting discovery server backoff  attempt # 0  retrying in  2  seconds
contacting discovery server backoff  attempt # 1  retrying in  4  seconds
22 Oct 14:33:11 - [error] [OPCUA-IIoT-Read:711ff8f6.1f7df] Error: Client Not SESSIONACTIVE On Read
22 Oct 14:33:11 - [error] [OPCUA-IIoT-Read:5975b607.1f0de8] Error: Client Not SESSIONACTIVE On Read
contacting discovery server backoff  attempt # 2  retrying in  8  seconds
contacting discovery server backoff  attempt # 3  retrying in  16  seconds
contacting discovery server backoff  attempt # 4  retrying in  32  seconds
 Server State =  Running
 Server State =  Running
contacting discovery server backoff  attempt # 5  retrying in  50  seconds
contacting discovery server backoff  attempt # 6  retrying in  50  seconds
22 Oct 14:35:11 - [error] [OPCUA-IIoT-Read:711ff8f6.1f7df] Error: Client Not SESSIONACTIVE On Read
22 Oct 14:35:11 - [error] [OPCUA-IIoT-Read:5975b607.1f0de8] Error: Client Not SESSIONACTIVE On Read
contacting discovery server backoff  attempt # 7  retrying in  50  seconds
contacting discovery server backoff  attempt # 8  retrying in  50  seconds
22 Oct 14:37:11 - [error] [OPCUA-IIoT-Read:711ff8f6.1f7df] Error: Client Not SESSIONACTIVE On Read
22 Oct 14:37:11 - [error] [OPCUA-IIoT-Read:5975b607.1f0de8] Error: Client Not SESSIONACTIVE On Read
contacting discovery server backoff  attempt # 9  retrying in  50  seconds
contacting discovery server backoff  attempt # 10  retrying in  50  seconds
Server: closing SESSION  active Session1  because of timeout =  60000  has expired without a keep alive
channel =  ::ffff:127.0.0.1  port =  64422
Server: closing SESSION  active Session1  because of timeout =  60000  has expired without a keep alive
channel =  ::ffff:127.0.0.1  port =  64425
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  4
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
 Security token has really expired and shall be discarded !!!! (lifetime is =  120000 )
 Server will now refuse message with token  1
22 Oct 14:58:09 - [error] [OPCUA-IIoT-Read:711ff8f6.1f7df] Error: Client Not SESSIONACTIVE On Read
22 Oct 14:58:09 - [error] [OPCUA-IIoT-Read:5975b607.1f0de8] Error: Client Not SESSIONACTIVE On Read
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
 warning : ClientSessionKeepAliveManager#ping_server   ServiceResult is BadSessionIdInvalid (0x80250000) request was ReadRequest
 warning : ClientSessionKeepAliveManager#ping_server   ServiceResult is BadSessionIdInvalid (0x80250000) request was ReadRequest
22 Oct 14:58:09 - [info] Stopping modified nodes
22 Oct 14:58:09 - [info] Stopped modified nodes
22 Oct 14:58:09 - [info] Starting modified nodes
22 Oct 14:58:09 - [info] Started modified nodes
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
22 Oct 14:58:09 - [warn] Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)
contacting discovery server backoff  attempt # 11  retrying in  50  seconds
contacting discovery server backoff  attempt # 12  retrying in  50  seconds
contacting discovery server backoff  attempt # 13  retrying in  50  seconds
22 Oct 15:01:49 - [error] [OPCUA-IIoT-Read:711ff8f6.1f7df] Error: Client Not SESSIONACTIVE On Read
22 Oct 15:01:49 - [error] [OPCUA-IIoT-Read:5975b607.1f0de8] Error: Client Not SESSIONACTIVE On Read
   
Using windows 10

node version 10.16
node red v0.20.8
node-red-contrib-iiot-opcua -2.7.1

**Comment by biancode** [comment]
Please, try the new version v3.11.3 or above and let's go ahead with that version.
