### ISSUE TITLE
Browser node doesn't work without a payload

### ISSUE THREAD

**Issue by Pulssi** [BiancoRoyal/node-red-contrib-iiot-opcua#119]
**I'm submitting a ...**  (check one with "x")
   
## Feature
 - ( ) feature request
 
 **What is the motivation or Use Case for your feature request?**
 
 
 

## Support
 - support request => **Please do not submit support requests here**, instead see use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer)
 - ( ) simple question => please visit the Wiki and Info tab by clicking on the node inside Node-RED before
 - FAQ: Can I send you individual support requests via E-Mail? 
   - Yes, sure! :-D
   
   
   

## Problem
 - ( ) bug report => please search GitHub for a similar issue or PR before submitting
 - ( x ) unexpected behaviour => please visit the Wiki before

### Information
 **Current behaviour**
If you send a msg without a payload property to browser node you'll get error saying "TypeError: Cannot read property 'actiontype' of undefined". After setting payload property it works.
 
 **Expected behaviour**
Sending a msg object with just a addressSpaceItems property as instructed in browser node info would work fine. Or browser node info tab would tell about a payload property being required.
 
 **Minimal reproduction of the problem with instructions**
Just send some msg without a payload property to browse node.
   

#### Your Environment
**Please tell us about your environment:**

  * ( x ) I am using just the Node-RED package and got node-opcua installed with it
  * ( ) I have installed node-opcua global from source (using git clone)
  * ( ) I have installed node-opcua as a global package (using npm i -g) 
  
  * Device :
    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( x ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting OPC UA system:
   Not sure what this means...?

     
* **Node-RED version:** 
0.20.8

* **node-red-contrib-iiot-opcua version:** ``
3.12.0

* **Node:** (min. 8.x)
   `node --version` = 10.7

**Comment by biancode** [comment]
That is not a bug for me. The node has an interface, which has to be filled. It could check more to get a clear message.
