### ISSUE TITLE
How To send a dynamic value to a node connector?

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#12]
I want to set the value in the node connector dynamically, which output structure should I fill to populate the node data value from an input msg.payload.d.value field?

**Comment by chminngi** [comment]
To clarify more I want extract a previous computed or received msg item value (e.g. 80) and inject it into any  IIOT nodes that can handling data values (node, ...).
If you provide hooks like msg.value or something similar, the user can pass dynamic data to a placeholder without taking care where to fill the data in your node.

Can you implement this for all values that can be changed programmatically?

Can you provide something for node that I can test?

**Comment by biancode** [comment]
Please, use the structure as it is. From my point it is all there to send dynamic data. All work of the inject could be done by the event message. It is not clearly to see, what you are missing or searching for.

**Comment by chminngi** [comment]
Should I use nodesTowrite.value.value.value for injecting the value?
It is not so clear explained how to inject a dynamic value.

**Comment by biancode** [comment]
nodesToWrite is to fill as an Array of values and objects ... why do you think you have to use nodesTowrite.value.value.value?

**Comment by chminngi** [comment]
Looking into the debug node I could see a value object that is nested into another value object and at least the value item with the data in it.

**Comment by biancode** [comment]
I am sorry, but maybe you are at the wrong place to debug?!

![image](https://user-images.githubusercontent.com/4369867/36737938-94420d80-1bdc-11e8-961b-6540b0232856.png)

**Comment by biancode** [comment]
please reopen if you need more ...
