### ISSUE TITLE
**Address Space Script** of OPC UA server with Boolean, String or Datetime

### ISSUE THREAD

**Issue by EngDiego** [BiancoRoyal/node-red-contrib-iiot-opcua#120]
Hello, I trying use **Address Space Script** of OPC UA server with Boolean, String or Datetime but ins`t working. Could you help, what i need to do in code bellow to work?
(with Byte, float, double, Int16,32.... works)

	const gsamTopCyc = namespace.addVariable({
	  "organizedBy": samFolder,
	  "browseName": "TopCyc",
	  "nodeId": "ns=1;s=TopCyc",
	  "dataType": "Boolean",    <<===
		"value": {
		  "get": function() {
			return new Variant({
			  "dataType": DataType.Boolean,  <<===
			  //"value": enable
			  "value": flexServerInternals.sandboxFlowContext.get("samTopCyc")
			});
		  },
		  "set": function(variant) {
			flexServerInternals.sandboxFlowContext.set(
		"samTopCyc",
			  parseFloat(variant.value)
			);
			return opcua.StatusCodes.Good;
		  }
		}
		});

**Comment by UlrichEntrenco** [comment]
Hi, I got the same issue. Is it a typo or is the datatype "boolean" not implemented yet?
Thanks!

**Comment by biancode** [comment]
@UlrichEntrenco the type is implemented, but there is maybe a change and it does not work as expected anymore.

**Comment by biancode** [comment]
please, try the new node-red-contrib-opcua-server
