### ISSUE TITLE
searching manual for address space modelling

### ISSUE THREAD

**Issue by CarOswald** [BiancoRoyal/node-red-contrib-iiot-opcua#121]
Hello,

I try to set up a umati address space model. To do so in need to change the namespace-infos and also methods, folders and objects.
Is a manual for setting up a configuration with all features available?
How to add a variable to a specified folder, made previous?
How to build a Method?
All this things are documentated somewhere, but where?
Any hint is very welcome.

Kind regards,

Carsten

**Comment by biancode** [comment]
Hello Carsten,

with the actual version, there is some to test and maybe to program to add other specs.
It would be easier if we had time to add node-opcua v2.x for that.

Kind regards,
Klaus

**Comment by biancode** [comment]
Please, reopen if you want to support as a sponsor.
