### ISSUE TITLE
How to use setTimeout in address space script of OPC-UA-IIot-Flex-Server-Node?

### ISSUE THREAD

**Issue by JanSchmidtm** [BiancoRoyal/node-red-contrib-iiot-opcua#122]
Hello, 
I am trying to use a setTimeout-object in address space script of OPC-UA-IIoT-Flex-Server-Node but it isn`t working (see figure below). I get always a failure "Server Address Space Failure". Without the setTimeout-object everything works fine. How to implement timeouts in address space script?

Version of node-red-contrib-iiot-opcua: 3.12.0
Version of node-red: v1.0.3

![OPC-UA-IIot-Flex-Server-Node](https://user-images.githubusercontent.com/60974252/74348130-8212a980-4db2-11ea-8fd8-3ff039f077d1.PNG)

Kind regards,

Jan

**Comment by biancode** [comment]
My new package `node-red-contrib-opcua-server` has it.

**Comment by JanSchmidtm** [comment]
Great, thanks for the information :-). 
It works!
