### ISSUE TITLE
Make Listener work with Browse Result

### ISSUE THREAD

**Issue by araisch** [BiancoRoyal/node-red-contrib-iiot-opcua#13]
First of all thanks for your great work with this plugin. I love it.

Problem: If you want to transfer huge amounts of variables to a sink with limited afford, it's working great with Browse & Read. The drawback is, that you spam the sink with lot of near-static values (with changes less then once a day) with the given polling rate. 
Solution: Make the Listener node work with Browse results, like the Read node does already today.

Right, I could code a function transforming a Browse result to a msg-style the Listener is able to read by myself. But subscribe is such a great function for minimizing data from opc ua that this might be a nice enhancement for other users as well.

**Comment by biancode** [comment]
Thank you!

It is not clearly, what are you want to do. In normal case you send one subscription to all variables to listen for. Then the Listener works as your settings set the options (publish, sample interval ...) - means you do not need a next inject to the listener from here if you just want to listen to the same variables all the time.

Please, describe more in detail, what is expected!

cya
Klaus

**Comment by araisch** [comment]
The flow to poll many variables at once looks like that:
![grafik](https://user-images.githubusercontent.com/35069589/36840817-a8009ed4-1d46-11e8-99ef-28ca0d143ae1.png)
The flow to subscribe many variables at once should look like that (in my opinion):
![grafik](https://user-images.githubusercontent.com/35069589/36840885-dc92d00e-1d46-11e8-99f4-afe15889a25c.png)

But that does not work. Therefore i have to enter all the UA-nodeIDs manually in the inject node and do it like that:
![grafik](https://user-images.githubusercontent.com/35069589/36841012-2f1696a8-1d47-11e8-90eb-516cce8e8ecf.png)

To generate the variable-list for Listening automatically and keep it on date (when add or remove UA-Nodes from the server) the approach with Inject -> Browse -> Listen would be great. In other words: The Listener should be able to deal with the output message of the Browser, like the Read-Node does.

**Comment by biancode** [comment]
like that?

![image](https://user-images.githubusercontent.com/4369867/36860016-8454a680-1d80-11e8-9d8e-315b61a4cbdf.png)

**Comment by biancode** [comment]
please test v2.0.12 or above

**Comment by biancode** [comment]
Take a look to the whole msg object. There you will find more information.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by araisch** [comment]
It is the whole msg object. There is just the _msgid outside of the payload.
Like I said: In the upper output message there is an array "addressSpaceItem" with the field "nodeID". But this message contains also huge arrays input.addressSpaceItem and input.nodesToRead. 

In my opinion the "Send just values" property in the "Listener"-Node makes no sense. For me it should be like:

- "Send just values" is ticked: The Listener just sends the light-weight message I screenshoted above (with added field containing the node-ID).
- "Send just values" is not ticked: The Listener sends the big message with all the information.
Reason: I'm not sure if there is an influence on performance if you spam this huge message hundred times a second. On a big machine there will be no problem. But assume that you run this on a small "on-the-edge"-Device for connecting an OPC-UA-Device to IoT with transfering hundreds of variables a second. I have the fear to book out the device with that hundreds of huge messages.

Therefore my suggest: One option for big machines with that huge all-containing message (you provide already at the upper output) and one option for light-weight on-the-edge devices with a minimum footprint message (you provide already at the lower output+nodeID). And the user can choose with the "Send just values" property.
![grafik](https://user-images.githubusercontent.com/35069589/36890781-799b2690-1dff-11e8-9a38-825da1a2c0be.png)

**Comment by biancode** [comment]
Send just values off

![image](https://user-images.githubusercontent.com/4369867/36903383-ddf38244-1e2d-11e8-94cf-6b33967660fe.png)

**Comment by araisch** [comment]
This is the message of the upper output.
![image](https://user-images.githubusercontent.com/35069589/36903890-504c8592-1e2f-11e8-83fd-bc6801ddd065.png)
If you subscribe 1000 variables it generates at least on start-up 1000 messages with the content:
![image](https://user-images.githubusercontent.com/35069589/36903576-739d71ce-1e2e-11e8-86d6-2b5106d7aa6e.png)
And all the 1000 messages will have two arrays with again 1000 objects each (yellow highlighted in screenshot). This means **2 Millions objects are generated at once**. For small devices this could be a problem. 
So my point is:
- Property to switch on/off this upper output. But not just the output itself, the creation of those objects internal as well. 
- Give the lower output a new field named node-ID, because the lower output is really fine. Enough for 99% of all users and still very small. But there is no way to identify the variable, yet.

**Comment by biancode** [comment]
Yes, you are right and I know that. I am working on the structures step by step. The API of node-opcua becomes more easy so it will become less spam in the future in communication, but I need time to do all the work ;)

**Comment by biancode** [comment]
next version event msg

![image](https://user-images.githubusercontent.com/4369867/36909478-5cc7b4c2-1e3e-11e8-8273-b6add24cd862.png)

**Comment by biancode** [comment]
next version monitor msg 1 & 2

![image](https://user-images.githubusercontent.com/4369867/36909540-8e3e1906-1e3e-11e8-93b3-b8ff3f42655c.png)

**Comment by biancode** [comment]
please test with v2.1.0
