### ISSUE TITLE
Automate NPM publishing

### ISSUE THREAD

**Issue by ghost** [BiancoRoyal/node-red-contrib-iiot-opcua#136]
### Describe the requested feature

The `Build and Summary` action defined in the `build.yml` workflow has a placeholder stage for publishing new versions to npm. 

- [x] Add the rest of the NPM publishing steps to the `publish` step.
- [x] Ensure the `publish` step is only triggered when pushing to tags.
- [x] Add necessary tokens to the project Secrets

### Motivation

Simplify the process of publishing updates to NPM.

**Comment by biancode** [comment]
done since v4.0.x
