### ISSUE TITLE
Version Bump: node-opcua 2.64.1 to 2.74+

### ISSUE THREAD

**Issue by ghost** [BiancoRoyal/node-red-contrib-iiot-opcua#140]
### Describe the requested feature

It may be a good idea to wait with this until e2e tests are working properly.

- [ ] Ensure 2.74+ doesn't contain any breaking changes for any nodes

### Motivation

Keep node-opcua updated to latest releases.

**Comment by dtq-one** [comment]
we have seen some issues early on with the very latest `2.68.1` node-opcaua package and hence pinned to `2.64.1` 

that said, we have not seen those problems recently but still advocate for making all e2e tests #137 work again (locally and via CI pipeline) before embarking in upgrading all packages to latest (ie dependabot)
