### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by CapicciS** [BiancoRoyal/node-red-contrib-iiot-opcua#15]
Hallo,

I ‘am at the beginning of my experience with node.js and node-red. I would like to communicate with an OPC-UA Server and I want to use your package in Node-red. But I have trouble to install that.
Here is a copy of the important part (so I think) of the log file:

3373 warn node-red-project@0.0.1 No repository field.
3374 warn node-red-project@0.0.1 No license field.
3375 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\Administrator\.node-red\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\Administrator\.node-red\node_modules\npm\node_modules\.ansistyles.DELETE'
3376 verbose cwd C:\Users\Administrator\.node-red
3377 verbose Windows_NT 6.1.7601
3378 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-red-contrib-iiot-opcua"
3379 verbose node v9.7.0
3380 verbose npm  v5.6.0
3381 error path C:\Users\Administrator\.node-red\node_modules\npm\node_modules\ansistyles
3382 error code ENOENT
3383 error errno -4058
3384 error syscall rename
3385 error enoent ENOENT: no such file or directory, rename 'C:\Users\Administrator\.node-red\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\Administrator\.node-red\node_modules\npm\node_modules\.ansistyles.DELETE'
3386 error enoent This is related to npm not being able to find a file.
3387 verbose exit [ -4058, true ]

This is the result of a local (node-red dir) installation. The global installation done ok, but nod-red makes trouble. "Waiting for missing types to be registered:"
![grafik](https://user-images.githubusercontent.com/28596792/36903462-114b6ac6-1e2e-11e8-8076-398219518f81.png)

They have any problem with this directory 'C:\Users\Administrator\.node-red\node_modules\npm\node_modules\ansistyles'? But I don't know!
node-red version: v0.18.4
OS: Windows Embedded Standard 7 x86

I hope you can help me.
Mario

**Comment by biancode** [comment]
Hi Mario,

I'm sorry, but that is a problem on Windows and Node.js - I'm not enough experienced with Windows.
Please use the Node-RED Slack channel. There you will find very fast advice.

Happy installing!
Klaus
