### ISSUE TITLE
modified inject node timer at start not effective

### ISSUE THREAD

**Issue by ouinouin** [BiancoRoyal/node-red-contrib-iiot-opcua#158]
### Which node-red-contrib-iiot-opcua version are you using?

4.0.1

### What happened?

the modified inject node seems to work only manually, when you tick the delay at start box and you add some delay, it doesnt work, i noticed this while using the sdm 630 example  , none of the inject nodes seems to be working 

### Server

OPCUA-IIoT-Server Node

### How can this be reproduced?

use the example with sdm630 and see if the folders are created in the server with an opcua viewer

### What did you expect to happen?

the delay should work from the flow reload.

### Other Information

nodered V2.2.2  node V16.15.1

**Comment by biancode** [comment]
E2E tests were disabled in TypeScript migration and is now active again see https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/issues/168 - works since [tag v4.0.7](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/releases/tag/v4.0.7)
