### ISSUE TITLE
Cannot delete original objects from server

### ISSUE THREAD

**Issue by tsangiotis** [BiancoRoyal/node-red-contrib-iiot-opcua#16]
Hello,

I cannot figure out how to delete the original example objects from the server.

- Bianco Royal
- Device Set
- Server*
- Tanks

* I assume _Server_ is needed for OPC UA to work.

**Comment by biancode** [comment]
Yes, Device Set and Server are part of the OPC UA server and not to delete.

delete the Bianco Royal and Tanks folder via Command :

![image](https://user-images.githubusercontent.com/4369867/36935469-6381daa8-1ef8-11e8-8ad1-00f737151ca2.png)

**Comment by tsangiotis** [comment]
It seems like I cannot get this to work.

Here are screenshots of my setup:

![issue0](https://user-images.githubusercontent.com/697354/36935698-926204aa-1f03-11e8-9621-27123c2d38a7.PNG)
![issue1](https://user-images.githubusercontent.com/697354/36935699-928ca7c8-1f03-11e8-8993-3e562e388413.PNG)
![issue2](https://user-images.githubusercontent.com/697354/36935700-92ae0b66-1f03-11e8-94a9-a125499974bf.PNG)

**Comment by biancode** [comment]
Please, send the flow or an example.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
