### ISSUE TITLE
[[Meeting]] Notes from 2022-07-15 meeting

### ISSUE THREAD

**Issue by dtq-one** [BiancoRoyal/node-red-contrib-iiot-opcua#164]
## Roadmap / nächste Schritte

- get e2e working reliably for all nodes
- test (and possibly estend) all examples
- get automated publishing to npmjs working
  - depends on: release management
  - maybe use: git flow; alternatives
- refactoring
  - make current implementation more Node-RED idiomatic
  - proper usage of payload "what data goes where" 
  - flow forge?
- new features
  - method node (nodeopca has gained much better support for this)
  - pub/sub? - talk to Etienne 
- revise and update documentation
  - GH pages?
  - Wiki

**Comment by biancode** [comment]
fixing e2e tests soon from v4.1.x if we find time to work on it
