### ISSUE TITLE
[BUG] Misspelling (msg.poyload ====> msg.payload)

### ISSUE THREAD

**Issue by lxmuyu** [BiancoRoyal/node-red-contrib-iiot-opcua#189]
### Which node-red-contrib-iiot-opcua version are you using?

4.0.2

### What happened?

<div class="f4 text-normal" style="box-sizing: border-box; font-size: 16px !important; font-weight: 400; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a title="src/opcua-iiot-listener.ts" data-hydro-click="{&quot;event_type&quot;:&quot;search_result.click&quot;,&quot;payload&quot;:{&quot;page_number&quot;:1,&quot;per_page&quot;:10,&quot;query&quot;:&quot;poyload&quot;,&quot;result_position&quot;:1,&quot;click_id&quot;:94613846,&quot;result&quot;:{&quot;id&quot;:94613846,&quot;global_relay_id&quot;:&quot;MDEwOlJlcG9zaXRvcnk5NDYxMzg0Ng==&quot;,&quot;model_name&quot;:&quot;Repository&quot;,&quot;url&quot;:&quot;https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/e7c5d7f4a1ba19382e0ade67575253c78907e662/src/opcua-iiot-listener.ts&quot;},&quot;originating_url&quot;:&quot;https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/search?q=poyload&quot;,&quot;user_id&quot;:32975142}}" data-hydro-click-hmac="d1f1ab205f6920aa0101ca6eced481a3cf418bea4a0d2f56ec2fe7738be0c4e8" href="https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/e7c5d7f4a1ba19382e0ade67575253c78907e662/src/opcua-iiot-listener.ts" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">src/opcua-iiot-listener.ts</a></div><div class="file-box blob-wrapper my-1" style="box-sizing: border-box; margin-top: 4px !important; margin-bottom: 4px !important; overflow: auto hidden; border: 1px solid var(--color-border-default); border-radius: 6px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

489 | try {
-- | --
490 | RED.util.setMessageProperty(msg.poyload, 'value', JSON.parse(dataValuesString))
491 | } catch (err: any) {

</div>

Misspelling (msg.poyload ====> msg.payload) 

### Server

OPCUA-IIoT-Server Node

### How can this be reproduced?

Allways

**Comment by biancode** [comment]
fixed with next v4.0.9
