### ISSUE TITLE
Bug in BuildVariant (opcua-iiot-core.ts): Values like 0, 0.0, or false result in null (or NaN) values

### ISSUE THREAD

**Issue by dei-p4i** [BiancoRoyal/node-red-contrib-iiot-opcua#190]
### Which node-red-contrib-iiot-opcua version are you using?

4.0.9

### What happened?

We encountered getting #NaN as values on our OPC UA Server, when using the write node, if the value was 0.0.
Further testing showed that also 0 (for int types) and false (for boolean) resulted in null errors.
_Note:_ Before updating to 4.0.9 we used a 3.x.x version without that problem (don't remember exact version)

I found a probable problematic line of code in the package source: 
the if-test in the beginning of `buildNewVariant` in [/src/core/opcua-iiot-core.ts](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/src/core/opcua-iiot-core.ts):
```export function buildNewVariant(datatype: DataTypeInput, value: any): DataValueOptions {
  let variantValue: VariantOptions = {
    dataType: DataType.Null,
    value: null
  }
  // Possible bug location:
  // javascript interprets 0, 0.0 and false (or empty arrays or ...) here as false, so value stays "null"
  if (value.value)
    value = value.value
```
### Server

OPCUA-IIoT-Flex-Server Node (Please attach AddressSpaceScript to the next section)

### How can this be reproduced?

Zipped Demo with Flex-Server using (slightly modified) original addressSpace code:
[demo-iiot-opcua-zero-value-bug.json.zip](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/9259691/demo-iiot-opcua-zero-value-bug.zip)

- Set value to 1.0 by inject => read by inject => value is 1.0
- Set value to 0.0 by inject => read by inject => value is null

### What did you expect to happen?

Value should be 0.0 (or 0 or false depending on used data type)

**Comment by biancode** [comment]
It would be good to have tests for this issue.

**Comment by CW0815** [comment]
opc.tcp://milo.digitalpetri.com:62541/milo 
ns=2;s=CTT/Static/All Profiles/Scalar/Int16 

Write
Set value to 1 by inject (value is 1)
Set value to 0 by inject ("Error: expecting a number NaN")
Set value to "0" by inject (value is 0)

Read
read 1 by inject (msg.payload.value[0].value is 1)
read 0 by inject (msg.payload.value[0].value.value is 0)

**Comment by biancode** [comment]
We working on a version 4.1 - we found a lot issues after the TS merge, which are to be fixed soon.

**Comment by CW0815** [comment]
same problem with version 4.1

opc.tcp://milo.digitalpetri.com:62541/milo
ns=2;s=CTT/Static/All Profiles/Scalar/Int16

Write
Set value to 1 by inject (value is 1)
Set value to 0 by inject ("Error: expecting a number NaN")
Set value to "0" by inject (value is 0)

Read
read 1 by inject (msg.payload.value[0].value is 1)
read 0 by inject (msg.payload.value[0].value.value is 0)

**Comment by biancode** [comment]
We did not work on that for now. Maybe we have it next week in our next release.

**Comment by biancode** [comment]
@JoelKrec we should include this as a test in the package.

**Comment by biancode** [comment]
v4.1.1 actual test - release soon

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4369867/206644530-3fd4ffa8-10d3-40f5-914a-b0e2e32a45ac.png">

**Comment by biancode** [comment]
Test Flow to implement in e2e testings

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4369867/206645457-cc1f1656-3fab-4dea-afd5-66c103fffb55.png">

[TestFlowZeroValueBug.json.zip](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/10192573/TestFlowZeroValueBug.json.zip)

**Comment by CW0815** [comment]
v4.1.1 the value is null, but with "OPCUA-IIoT-Inject" + "function" the value is 0

msg.payload.nodetype = 'inject';
msg.payload.injectType = 'write'

msg.payload.valuesToWrite = [];
msg.payload.valuesToWrite[0] = "0";

return msg;

![Test_Zero_01](https://user-images.githubusercontent.com/111639455/207696199-d3d47884-a4d8-47b2-b87d-25ec643dc7e9.png)
[TestFlowZeroValueBug02.zip](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/files/10231073/TestFlowZeroValueBug02.zip)

**Comment by biancode** [comment]
@CW0815 give v4.1.2 a try

**Comment by CW0815** [comment]
This works with v4.1.2

But with a Response between Read and helper,
the output is different at 0 and 1.

![Test_Zero_03](https://user-images.githubusercontent.com/111639455/207941005-824adeea-f26e-41bb-ac10-ea612ac04b99.png)

**Comment by biancode** [comment]
The response node is not working very well after the shift to TypeScript. See the [TODO.md](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/blob/master/TODO.md) for more information.
