### ISSUE TITLE
Magnifying Glass Dropdown Help Button not working - OPC UA IIot Nodes

### ISSUE THREAD

**Issue by NickNol17** [BiancoRoyal/node-red-contrib-iiot-opcua#253]
Hey Everyone ! :slightly_smiling_face:

I'm quite new to this Node Red Thing and experienced an annoying ?Bug? in my NodeRed Frontend.

![](https://global.discourse-cdn.com/business6/uploads/nodered/original/3X/9/6/9662a747f0ff64820c0fb7722afbe1646a24b1b2.png)

I can't use the Dropdown Menu properly to see/check if my inserts are the right way.
Yet, I didn't find a solution for this. I installed NodeRed on my Raspberry Pi 400 ans also on my 2019 MacBook Pro. Tested it with Safari and Chrome. No Dropdown / Magnifying Glass Button available.

Does anybody know how to fix this?

Thank u in advance!

Regards!

Nick

**Comment by JoelKrec** [comment]
Hello @NickNol17 

For me and other users on multiple computers and architectures, this feature is working. To be able to help you, I need to have some more information. 

For example you could look at the network traffic of the page with browser developer tools. The button makes a REST request to the backend. If this call returns without an error, then there is probably a bug in the code. If not, then I need the error number and a bit more information about what is working and what isnt. Also a bit more information about your systems would help. 

Have you only used the magnifying glass on already filled values? The dropdown menu deletes options that you already typed or options that do not fit to the typed value. In the image there are correct data types and therefore, the magnifying glass should not do anything iirc.
