### ISSUE TITLE
Security Policy Not support Basic256

### ISSUE THREAD

**Issue by gaoyuan533515** [BiancoRoyal/node-red-contrib-iiot-opcua#277]
### Describe the requested feature

The Security Policy attribute of OPCUA-IIoT-Connector does not support Basic256. We would like to add support for Basic256.
Basic256Rsa15 and Basic256Sha256 cannot be used on some Siemens CNC machines
### Motivation

Many Siemens CNC machines only support Basic256.Basic256Rsa15 and Basic256Sha256

**Comment by biancode** [comment]
#259
