### ISSUE TITLE
[error] [OPCUA-IIoT-Connector:OPCServer] TypeError: Cannot read property 'join' of null

### ISSUE THREAD

**Issue by Sh0ku** [BiancoRoyal/node-red-contrib-iiot-opcua#3]
Hello,
i get this error when i try to connect to a specific OPC UA server. So theoreticaly it could be a fault from the server but I have no specific idea where the error is from after hours of searching. I hope someone here can help me.

Security Policy and Security Mode are both None. Credentials are used.

My setup is:
OS: Windows 7
Node.js: v8.9.2
Node-RED: v0.17.5
node-red-contrib-iiot-opcua: v1.3.3

> 22 Jan 14:02:10 - [info] Started flows
>  WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x1  but got 0x0  Class = OpenSecureChannelResponse
>  ERROR !!! , please check here !!!! callback may be called twice !!  TypeError: Cannot read property 'join' of null
>     at C:\Users\myUser\.node-red\node_modules\node-red-contrib-iiot-opcua\opcuaIIoT\maps\core\core\opcua-iiot-core-connector.js:101:47
>     at Array.forEach (<anonymous>)
>     at C:\Users\myUser\.node-red\node_modules\node-red-contrib-iiot-opcua\opcuaIIoT\maps\core\core\opcua-iiot-core-connector.js:93:15
>     at C:\Users\myUser\.node-red\node_modules\node-opcua-client\src\client_base.js:684:9
>     at modified_callback (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:986:28)
>     at process_request_callback (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:76:5)
>     at ClientSecureChannelLayer._on_message_received (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:122:5)
>     at emitMany (events.js:147:13)
>     at MessageBuilder.emit (events.js:224:7)
>     at MessageBuilder._decode_message_body (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\message_builder.js:442:22)
> 22 Jan 14:02:12 - [error] [OPCUA-IIoT-Connector:OPCServer] TypeError: Cannot read property 'join' of null
>     at C:\Users\myUser\.node-red\node_modules\node-red-contrib-iiot-opcua\opcuaIIoT\maps\core\core\opcua-iiot-core-connector.js:101:47
>     at Array.forEach (<anonymous>)
>     at C:\Users\myUser\.node-red\node_modules\node-red-contrib-iiot-opcua\opcuaIIoT\maps\core\core\opcua-iiot-core-connector.js:93:15
>     at C:\Users\myUser\.node-red\node_modules\node-opcua-client\src\client_base.js:684:9
>     at modified_callback (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:986:28)
>     at process_request_callback (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:76:5)
>     at ClientSecureChannelLayer._on_message_received (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:122:5)
>     at emitMany (events.js:147:13)
>     at MessageBuilder.emit (events.js:224:7)
>     at MessageBuilder._decode_message_body (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\message_builder.js:442:22)

"WARNING SERVER ..."  is posted every few seconds with, for me, random "expecting 0x**" 

Thanks in advance and if this error ist not from the client side forgive me 😄.
ManniMo

**Comment by biancode** [comment]
Hi ManniMo,

hm, the code lines from the stack trace are different. Are you sure to have 1.3.3 running?

<img width="616" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35230998-e984aba6-ff97-11e7-9820-0f8c427a2747.png">

It looks like a problem with that endpoints or with the `endpoint.server.discoveryUrls`.
Please, could you [record some logs](https://github.com/biancode/node-red-contrib-iiot-opcua/wiki/DEBUG) for the connector?

With the switch for logging, you should see what you get from the server.

Happy logging!
Klaus

**Comment by biancode** [comment]
<img width="346" alt="screen shot 2018-01-22 at 17 21 52" src="https://user-images.githubusercontent.com/4369867/35231332-ca189b46-ff98-11e7-854a-308638db0be7.png">

Please, watch on "Manage palette" in Node-RED, which version is running.

**Comment by biancode** [comment]
You could try the [opcua-commander](https://github.com/node-opcua/opcua-commander) too. we have the same base ;)

**Comment by Sh0ku** [comment]
Thanks for your quick answer.
I've duble checked the version number, it is 1.3.3. In adition, the installation is from yesterday with the node-RED palette manager, so i think it should be the newest stable build. I have checked the node-opcua version too, it is 0.1.1-0 in the package of this node. My only idea if this errors are from different versions is that i have an older version of node-opcua installed somewhere else but there nothing tries to connect to a server.
When i look at the debug log in node-red  it shows me:

> "Error: connect ETIMEDOUT ip"
>"Error stopping node: TimeoutError: timed out after 15000ms"
>"TypeError: Cannot read property 'join' of null"

edit: I have tried to connect with the UA Expert client and got the error
>Error 'BadSecurityModeInsufficient' was returned during ActivateSession, press 'Ignore' to suppress the error and continue connecting.

After pressing "Ignore" it works fine. Could it be, that the nodes cannot ignore this error?  

After a long time trying I've got DEBUG running. But i did not get it to push into a log file, so I copied the windows shell. I hope that it holds enought lines to get the error.

>   express:router:layer new '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/event/types' +7ms
  express:router:layer new '/opcuaIIoT/event/types' +1ms
  express:router:route get '/opcuaIIoT/event/types' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/event/types' +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/browser/:id/rootid/:rid' +58ms
  express:router:layer new '/opcuaIIoT/browser/:id/rootid/:rid' +1ms
  express:router:route get '/opcuaIIoT/browser/:id/rootid/:rid' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/browser/:id/rootid/:rid' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/object/InstanceTypes' +17ms
  express:router:layer new '/opcuaIIoT/object/InstanceTypes' +1ms
  express:router:route get '/opcuaIIoT/object/InstanceTypes' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/opcuaIIoT/object/InstanceTypes' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/opcuaIIoT/object/VariableTypeIds' +1ms
  express:router:layer new '/opcuaIIoT/object/VariableTypeIds' +1ms
  express:router:route get '/opcuaIIoT/object/VariableTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/object/VariableTypeIds' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/opcuaIIoT/object/ReferenceTypeIds' +1ms
  express:router:layer new '/opcuaIIoT/object/ReferenceTypeIds' +0ms
  express:router:route get '/opcuaIIoT/object/ReferenceTypeIds' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/opcuaIIoT/object/ReferenceTypeIds' +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:layer new '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/object/ObjectTypeIds' +3ms
  express:router:layer new '/opcuaIIoT/object/ObjectTypeIds' +0ms
  express:router:route get '/opcuaIIoT/object/ObjectTypeIds' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/opcuaIIoT/object/ObjectTypeIds' +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/object/VariableTypeIds' +0ms
  express:router:layer new '/opcuaIIoT/object/VariableTypeIds' +1ms
  express:router:route get '/opcuaIIoT/object/VariableTypeIds' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/opcuaIIoT/object/VariableTypeIds' +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/object/ReferenceTypeIds' +0ms
  express:router:layer new '/opcuaIIoT/object/ReferenceTypeIds' +1ms
  express:router:route get '/opcuaIIoT/object/ReferenceTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/object/ReferenceTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:layer new '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/opcuaIIoT/server/ISA95/specifications' +3ms
  express:router:layer new '/opcuaIIoT/server/ISA95/specifications' +1ms
  express:router:route get '/opcuaIIoT/server/ISA95/specifications' +1ms
  express:router:layer new '/' +0ms
  express:router:route get '/opcuaIIoT/server/ISA95/specifications' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/opcuaIIoT/object/DataTypeIds' +6ms
  express:router:layer new '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/object/DataTypeIds' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/opcuaIIoT/method/basicDataTypesForSelect' +5ms
  express:router:layer new '/opcuaIIoT/method/basicDataTypesForSelect' +1ms
  express:router:route get '/opcuaIIoT/method/basicDataTypesForSelect' +0ms
  express:router:layer new '/' +1ms
  express:router:route get '/opcuaIIoT/method/basicDataTypesForSelect' +1ms
  express:router:layer new '/' +0ms
 Setting debug for  factories_schema_helpers        to  false
 Setting debug for  factory_code_generator          to  false
 Setting debug for  factories                       to  false
 Setting debug for  ua_variable                     to  false
 Setting debug for  monitored_item                  to  false
 Setting debug for  tools_event_filter              to  false
 Setting debug for  ua_variable_type                to  false
 Setting debug for  argument_list                   to  false
 Setting debug for  message_builder                 to  false
 Setting debug for  tcp_transport                   to  false
 Setting debug for  client_tcp_transport            to  false
 Setting debug for  client_secure_channel_layer     to  false
 Setting debug for  client_base                     to  false
 Setting debug for  client_session                  to  false
 Setting debug for  opcua_client                    to  false
 Setting debug for  node_crawler                    to  false
 Setting debug for  client_subscription             to  false
 Setting debug for  opcua_server                    to  false
 Setting debug for  condition                       to  false
 Setting debug for  subscription                    to  false
 Setting debug for  server_publish_engine           to  false
 Setting debug for  server_session                  to  false
 Setting debug for  server_engine                   to  false
 Setting debug for  server_end_point                to  false
 Setting debug for  server_secure_channel_layer     to  false
 Setting debug for  base_server                     to  false
 Setting debug for  opcua_discovery_server          to  false
  socket.io:server initializing namespace / +0ms
  socket.io:server creating engine.io instance with opts {"path":"/ui/socket.io"} +2ms
  socket.io:server attaching client serving req handler +32ms
23 Jan 15:01:14 - [info] Dashboard version 2.7.0 started at /ui
  express:router:route new /\/library\/themes($|\/(.*))/ +2s
  express:router:layer new /\/library\/themes($|\/(.*))/ +0ms
  express:router:route get { /\/library\/themes($|\/(.*))/ fast_star: false, fast_slash: false } +1ms
  express:router:layer new '/' +1ms
  express:router:route get { /\/library\/themes($|\/(.*))/ fast_star: false, fast_slash: false } +0ms
  express:router:layer new '/' +1ms
  express:router:route new /\/library\/themes\/(.*)/ +1ms
  express:router:layer new /\/library\/themes\/(.*)/ +0ms
  express:router:route post { /\/library\/themes\/(.*)/ fast_star: false, fast_slash: false } +1ms
  express:router:layer new '/' +1ms
  express:router:route post { /\/library\/themes\/(.*)/ fast_star: false, fast_slash: false } +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/uisettings' +1ms
  express:router:layer new '/uisettings' +0ms
  express:router:route get '/uisettings' +1ms
  express:router:layer new '/' +1ms
  express:router:route new '/ui_base/js/*' +0ms
  express:router:layer new '/ui_base/js/*' +1ms
  express:router:route get '/ui_base/js/*' +0ms
  express:router:layer new '/' +1ms
  express:router:route new /\/library\/uitemplates($|\/(.*))/ +33ms
  express:router:layer new /\/library\/uitemplates($|\/(.*))/ +1ms
  express:router:route get { /\/library\/uitemplates($|\/(.*))/ fast_star: false, fast_slash: false } +1ms
  express:router:layer new '/' +1ms
  express:router:route get { /\/library\/uitemplates($|\/(.*))/ fast_star: false, fast_slash: false } +0ms
  express:router:layer new '/' +1ms
  express:router:route new /\/library\/uitemplates\/(.*)/ +1ms
  express:router:layer new /\/library\/uitemplates\/(.*)/ +0ms
  express:router:route post { /\/library\/uitemplates\/(.*)/ fast_star: false, fast_slash: false } +1ms
  express:router:layer new '/' +1ms
  express:router:route post { /\/library\/uitemplates\/(.*)/ fast_star: false, fast_slash: false } +0ms
  express:router:layer new '/' +1ms
23 Jan 15:01:15 - [warn] ------------------------------------------------------
23 Jan 15:01:15 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
23 Jan 15:01:15 - [warn] [tail] Not currently supported on Windows.
23 Jan 15:01:15 - [warn] ------------------------------------------------------
23 Jan 15:01:15 - [info] Settings file  : \Users\myUser\.node-red\
settings.js
23 Jan 15:01:15 - [info] User directory : \Users\myUser\.node-red
23 Jan 15:01:15 - [info] Flows file     : \Users\myUser\.node-red\flows_NBVFPROENTWICK.json
  express:router use '/' query +23ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/ui/manifest.json' <anonymous> +1ms
  express:router:layer new '/ui/manifest.json' +0ms
  express:router use '/ui' serveStatic +2ms
  express:router:layer new '/ui' +0ms
23 Jan 15:01:15 - [info] Server now running at http://127.0.0.1:1880/
23 Jan 15:01:15 - [info] Starting flows
  opcuaIIoT:connector Connecting With Login Data On opc.tcp://123.123.123.00:16664 +0ms
  opcuaIIoT:inject Repeat Is  +0ms
  opcuaIIoT:inject Crontab Is  +1ms
23 Jan 15:01:15 - [info] Started flows
  opcuaIIoT:connector Connecting On opc.tcp://123.123.123.00:16664 +2s
  opcuaIIoT:connector:details Options {"securityPolicy":"None","securityMode":"NONE","defaultSecureTokenLifetime":60000,"keepSessionAlive":true,"connectionStrategy":{"maxRetry":15,"initialDelay":3000,"maxDelay":15000}} +0ms
 WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x1  but got 0x0  Class = OpenSecureChannelResponse
  opcuaIIoT:connector Connected On opc.tcp://123.123.123.00:16664 Options {"securityPolicy":"None","securityMode":"NONE","defaultSecureTokenLifetime":60000,"keepSessionAlive":true,"connectionStrategy":{"maxRetry":15,"initialDelay":3000,"maxDelay":15000},"certificateFile":"C:\\Users\\myUser\\.node-red\\node_modules\\node-opcua-client\\certificates\\client_selfsigned_cert_1024.pem","privateKeyFile":"C:\\Users\\myUser\\.node-red\\node_modules\\node-opcua-client\\certificates\\PKI\\own\\private\\private_key.pem"} +118ms
  opcuaIIoT:connector endpoint: opc.tcp://endpointname:16664 +10ms
  opcuaIIoT:connector Application URI: urn:unconfigured:application +2ms
  opcuaIIoT:connector:details Security Mode: NONE +129ms
  opcuaIIoT:connector:details securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None +1ms
  opcuaIIoT:connector:details endpoint: opc.tcp://endpointname:16664 +1ms
  opcuaIIoT:connector:details Application URI: urn:unconfigured:application +2ms

  opcuaIIoT:connector:details Product URI: http://open62541.org +1ms
  opcuaIIoT:connector:details Application Name: open62541-based OPC UA Application +1ms
  opcuaIIoT:connector:details Security Mode: NONE +1ms
  opcuaIIoT:connector:details securityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None +1ms
  opcuaIIoT:connector:details Type: SERVER +2ms
ERROR !!! , please check here !!!! callback may be called twice !!  TypeError: Cannot read property 'join' of null
    at C:\Users\myUser\.node-red\node_modules\node-red-contrib-iiot-opcua\opcuaIIoT\maps\core\core\opcua-iiot-core-connector.js:101:47
    at Array.forEach (<anonymous>)
    at C:\Users\myUser\.node-red\node_modules\node-red-contrib-iiot-opcua\opcuaIIoT\maps\core\core\opcua-iiot-core-connector.js:93:15
    at C:\Users\myUser\.node-red\node_modules\node-opcua-client\src\client_base.js:684:9
    at modified_callback (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:986:28)
    at process_request_callback (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:76:5)
    at ClientSecureChannelLayer._on_message_received (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\client\client_secure_channel_layer.js:122:5)
    at emitMany (events.js:147:13)
    at MessageBuilder.emit (events.js:224:7)
    at MessageBuilder._decode_message_body (C:\Users\myUser\.node-red\node_modules\node-opcua-secure-channel\src\message_builder.js:442:22)
23 Jan 15:01:17 - [error] [OPCUA-IIoT-Connector:OMD Grinder] TypeError: Cannot read property 'join' of null
 WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x4  but got 0x0  Class = OpenSecureChannelResponse
 WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x5  but got 0x0  Class = OpenSecureChannelResponse
 WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x6  but got 0x0  Class = OpenSecureChannelResponse
 WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x7  but got 0x0  Class = OpenSecureChannelResponse
  opcuaIIoT:connector Cannot reconnect, server endpoint is unknown +4m
  opcuaIIoT:connector !!!!!!!!!!!!!!!!!!!!!!!!  CONNECTION CLOSED !!!!!!!!!!!!!!!!!!! +3ms
ClientSecureChannelLayer: Warning: securityToken hasn't been renewed

**Comment by biancode** [comment]
Hi, what did you get from the [opcua-commander](https://github.com/node-opcua/opcua-commander)?

**Comment by Sh0ku** [comment]
Hi,
if I try the opcua-commander I get "WARNING SERVER responseHeader.requestHandle is invalid: expecting 0x* but got 0x0 Class = OpenSecureChannelResponse" where * is a counting hexadecimal up from 0x1.
But I can connect to the server this way.

**Comment by Sh0ku** [comment]
Could it be possible that iiot-opcua can't handle the Application URI of urn:unconfigured:Application? Since other clients (opcua-commander and i have tried UaExpert too today) respond with errors that can be ignored I think the server isn't configured correctly but it would be nice if that could be handled here too. 
From the UaExpert I get 
![grafik](https://user-images.githubusercontent.com/35484607/35629116-1d6e2552-069e-11e8-86dc-c1241b4a39e7.png)

**Comment by biancode** [comment]
looks like it is fixed in node-opcua 0.2.0, but there are some new issues, why it could not be updated for now [node-opcua issue](https://github.com/node-opcua/node-opcua/pull/394)

**Comment by Sh0ku** [comment]
That would be nice. Then I will wait until there is an update. Unfortunately I dont know how to edit Nodes to try 0.2.1 myself and publish it here

**Comment by Sh0ku** [comment]
I tried the new Version of this node now and it seems the error ist fixed. But it needs a huge amount of Time to connect to the server (about 1 minute). This is the new log: [Log](https://gist.github.com/ManniMo/1e4514b6371fd361b8c77551c00df4e9)

**Comment by biancode** [comment]
Wow! +17s to close ... but there is not a lot I can do for that problem - please check the open lib close behavior with the node-opcua lib and help to fix that by node-opcua
