### ISSUE TITLE
crashes when connecting to existing non-node.js server

### ISSUE THREAD

**Issue by sixdiamants** [BiancoRoyal/node-red-contrib-iiot-opcua#31]
I'm running a .NET standard server from the OPC-UA foundation. UAExpert can connect to the endpoint. However, when I connect a OPCUA-IIoT-Browser  to this server, node-red crashes. The server and node-opcua-client run on the same Ubuntu 16.04 machine.

> 12 Mar 14:27:07 - [red] Uncaught Exception:
> 12 Mar 14:27:07 - Error: EACCES: permission denied, open '/usr/local/lib/node_modules/node-red-contrib-iiot-opcua/node_modules/node-opcua-client/certificates/PKI/server_certificate0.pem'

 And indeed, the server certificate doesn't exist on the given location. 
I find these warnings suspicious:
`[warn] [node-red-contrib-opcua/OpcUa-Browser] Error: Cannot find module '_generated_/_auto_generated_ServerStatus'`

[nodeREDIIoTOPCUA.log](https://github.com/biancode/node-red-contrib-iiot-opcua/files/1803046/nodeREDIIoTOPCUA.log)

**Comment by biancode** [comment]
please try the [opcua-commander](https://github.com/node-opcua/opcua-commander) does it work?

**Comment by biancode** [comment]
and try v2.3.1
