### ISSUE TITLE
Problems with OPCUA Discovery

### ISSUE THREAD

**Issue by fedelodo** [BiancoRoyal/node-red-contrib-iiot-opcua#33]
Hi,
I'm running the latest version of the package, I've checked the discovery square in the Security tab on the Server node but when I connect with UA Expert  on the endpoint it says "Discovery GetEndpoint on <address> (BadCommunicationError)" and  "Discovery FindServers on <address> (BadCommunicationError)" . 
Is it a known issue?
Thanks in advance.

**Comment by biancode** [comment]
Hi,

please post your server flow!

on my side it works ...

<img width="300" alt="screen shot 2018-03-13 at 23 31 01" src="https://user-images.githubusercontent.com/4369867/37373387-b7943520-2716-11e8-8c81-4a51167f55cc.png">

**Comment by biancode** [comment]
... or you mean port 4840, right?

**Comment by biancode** [comment]
<img width="488" alt="screen shot 2018-03-13 at 23 33 46" src="https://user-images.githubusercontent.com/4369867/37373489-0854eca2-2717-11e8-87de-e63ea486653f.png">

**Comment by biancode** [comment]
comes with the next version as a new node - named discovery

<img width="342" alt="screen shot 2018-03-14 at 00 14 52" src="https://user-images.githubusercontent.com/4369867/37374738-d11e9e9e-271c-11e8-83da-6f20f0ed0bda.png">

![image](https://user-images.githubusercontent.com/4369867/37374742-d93375e6-271c-11e8-85e6-a9c061bbd137.png)

**Comment by biancode** [comment]
![image](https://user-images.githubusercontent.com/4369867/37374777-06efe5c8-271d-11e8-81dd-819552a9d824.png)

**Comment by biancode** [comment]
<img width="237" alt="screen shot 2018-03-14 at 00 16 53" src="https://user-images.githubusercontent.com/4369867/37374787-0d6f23dc-271d-11e8-8fef-905b0de2354c.png">

**Comment by biancode** [comment]
v2.3.0
