### ISSUE TITLE
OPC-UA aggregation server

### ISSUE THREAD

**Issue by w4tsn** [BiancoRoyal/node-red-contrib-iiot-opcua#34]
Maybe this is a feature request. I'll change the title accordingly, if so.

Is there a possibility to create an aggregation server with reference type from multiple servers?

The scenario would be to have multiple servers with distinct models and one central server that has to model all the sub-servers together, without the need of touching the central server every time a new sub-server comes to live.

**Comment by biancode** [comment]
node-opcua has a serverclient concept, but I need more time to devolp that feature ... Milestone 3.x / 4.x

**Comment by biancode** [comment]
feel free to contribute and send your pull request
