### ISSUE TITLE
No description item found using the browse node

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#4]
I can browse a top level OPC/UA directory successfully, looking into the array I am missing the description field on each item.  I am using version 1.3.3. 
Can you add this to the code?

**Comment by biancode** [comment]
Hi Giovanni, 

with node-opcua you have to browse 
and send the browse results to a read node to get that attributes you wanna get.

see and test the example flow in Node-RED:

<img width="1430" alt="screen shot 2018-02-06 at 17 23 05" src="https://user-images.githubusercontent.com/4369867/35870638-70a82db2-0b62-11e8-9408-858751daafb1.png">

**Comment by biancode** [comment]
API changed in node-opcua for readAllAttributes

**Comment by biancode** [comment]
if the [node-opcua issue v0.2.x](https://github.com/node-opcua/node-opcua/pull/394) is fixed it will work again:

<img width="449" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35875007-592389a0-0b6e-11e8-853f-2a7e8858adc4.png">

**Comment by biancode** [comment]
but browser result stay:

<img width="382" alt="grafik" src="https://user-images.githubusercontent.com/4369867/35875111-96e61d70-0b6e-11e8-97e9-a985e2d472fa.png">

**Comment by biancode** [comment]
Please, test v2.x+

**Comment by biancode** [comment]
please check v2.0.4 or above

**Comment by chminngi** [comment]
Thank a lot Klaus, I‘ll try it
