### ISSUE TITLE
[Question] How to configure Client to Write?

### ISSUE THREAD

**Issue by JoaoMCPereira** [BiancoRoyal/node-red-contrib-iiot-opcua#40]
I'm currently running a FLEX Server in a Raspberry Pi, and I want to Write to the Server through IOT2020 also with Node-RED.

This is my current configuration on Client side:

![capturar](https://user-images.githubusercontent.com/37218292/37538341-41883316-2948-11e8-98d9-bff4746deed6.PNG)

And in Connector node I got this configuration: 

![capturar1](https://user-images.githubusercontent.com/37218292/37538901-fe341ac4-2949-11e8-9af8-50f61a771d3c.PNG)

But I'm getting the following error "Error: Session Not Valid On Write", I'm sure this is the correct Endpoint because this is the one I'm using in UaExpert to check everything.
What I'm doing wrong?

**Comment by biancode** [comment]
Please, set the Show Errors to checked and watch debug tab. What is the message there?

**Comment by JoaoMCPereira** [comment]
This is the error I get

![capturar2](https://user-images.githubusercontent.com/37218292/37539849-d659c9c4-294c-11e8-9a7a-fc025af73d4f.PNG)

There is need any specific block, in Node-RED, to make the Client work? Like Server block or any other else?

**Comment by biancode** [comment]
Please, test the examples under Node-RED menu > Import > examples > iiot opcua. Does it work?

**Comment by biancode** [comment]
please test v2.3.1 and/or send your flows of both to me

**Comment by JoaoMCPereira** [comment]
Can you tell me what is the best way to test de v2.3.1? 
Run the 'npm install -g node-red-contrib-iiot-opcua' will upgrade it?

**Comment by biancode** [comment]
@JoaoMCPereira for me `npm update -g node-red-contrib-iiot-opcua` works too if the node-opcua did not change in minor, but if you got too much trouble or node-opcua changed in minor a clean uninstall and install is the best practice

**Comment by JoaoMCPereira** [comment]
@biancode I dont have any node-opcua module instaled in the Server or neither in the Client, I don't know that was needed. I should install this module first? Or just clean installation of node-red-contrib-iiot-opcua is needed? 
Sorry for my silly question, but I did not understand the relation between this two modules. I was thinkng that iiot-opcua was enough to run a fully OPC-UA communication.

**Comment by JoaoMCPereira** [comment]
@biancode I reinstalled node-red-contrib-iiot-opcua module with the v2.3.1 and now everything works like a charm, Thank you for the help.
