### ISSUE TITLE
Cannot access Address space script 

### ISSUE THREAD

**Issue by gln-gln** [BiancoRoyal/node-red-contrib-iiot-opcua#42]
Hi All , 
I am trying to deploy sample OPC server to collect data from field devices. I want to define a new information model for the OPC UA server. From the [node-opc](https://www.npmjs.com/package/node-red-contrib-iiot-opcua)  I see the address Space tab but however I do not see it in my installation . The OPC UA node version is 2.3.0. I am new to Node red and OPC UA  as well. Any suggestions on how to define new information model in the node ?

**Comment by biancode** [comment]
Hi, there are two servers - server and flex server - you are searching for the flex server.
