### ISSUE TITLE
Feature Request: Flex IIoT connector

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#44]
Hi Klaus,

I tested the new 2.3.3 lib it looks good. The browser and read node works great, I could extract all the data I am interested in. Listener, connector and session are even stable

The only thing I am missing is a flex IIOT connector where I can add the connection options via node event, like msg.topic in the browser.

This open a new event driven way how to use your lib and add flexibility to make abstract node red building blocks.

Thanks and congrats for the good work.

**Comment by biancode** [comment]
Hi Giovanni,

yes, like the flex connector for my Modbus package.

**Comment by biancode** [comment]
comes with v3.1.0
