### ISSUE TITLE
Reconnect failed on opc/ua server reboot

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#5]
After rebooting an OPC/UA server the write node can not reconnect displaying error

**Comment by biancode** [comment]
OK, not on my side. Do you have more information as displaying error? ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by biancode** [comment]
What about the delay in injecting? Maybe you sending the write too fast. The server needs some time to start depending on the power of the host.

**Comment by chminngi** [comment]
Hi Klaus,

I will come back as soon I can restart the hardware opc/ua server

**Comment by biancode** [comment]
please, reopen if you find more time ...
