### ISSUE TITLE
Writing Arrays via Write Node

### ISSUE THREAD

**Issue by thedraft** [BiancoRoyal/node-red-contrib-iiot-opcua#51]
**I'm submitting a ...**  

### Problem
 - ( ) bug report => please search github for a similar issue or PR before submitting
 - (x) unexpected behavior => please visit the Wiki before
 
I want to write an array using the Write Node, but only the first value of the array is written. I applied the structure of the message according to the help entry, maybe I'm missing something. I also tried the message structure from the wiki with arrayType "Array" and it didn't work properly.
 
 **Minimal reproduction of the problem with instructions**
   1. Sending the msg object to a connected write node:
       msg : Object
       object
       ----payload: object
       ----topic: "ns=0;s=inputSpectrum"
       ----nodetype: "write"
       ----injectType: "write"
       ----addressSpaceItems: array[1]
       ------0: object
       --------name: "inputSpectrum"
       --------nodeId: "ns=0;s=inputSpectrum"
       --------datatypeName: "Float"
       --------arrayTypeName: "Array"
       ----valuesToWrite: array[512]
   2. Monitor server via opcua-commander, only first value of the array is transmitted to the server

**Comment by biancode** [comment]
please, test with v3 and reopen if you got more information
