### ISSUE TITLE
How to build a historian?

### ISSUE THREAD

**Issue by AndreGuerra123** [BiancoRoyal/node-red-contrib-iiot-opcua#53]
Hello, I know it's up to the user to set the historian, however, I didn't find any documentation on how to do it. Maybe an example of the most basic types of data would be helpful.

Best regards, Andre

**Comment by biancode** [comment]
Hello Andre,

please fill out the template and describe more detailed, what you are searching!

![screen shot 2018-06-15 at 07 09 20](https://user-images.githubusercontent.com/4369867/41451015-209ac0e6-706b-11e8-9608-c94aed6e79b9.png)

**Comment by AndreGuerra123** [comment]
I think this should be reopened and a feature request be made;
