### ISSUE TITLE
topic is not passed through the listener node

### ISSUE THREAD

**Issue by chrbos** [BiancoRoyal/node-red-contrib-iiot-opcua#57]
### Problem
 - (x) bug report => please search github for a similar issue or PR before submitting
 - ( ) unexpected behavior => please visit the Wiki before
 
 **Current behavior**
 Listener node does not pass on topic. 
 
 **Expected behavior**
 Topic from original message should appear on the output of the listener (according to documentation)
 
 Managed to work around the issue by adding something like **node.topic = msg.topic;** at the top of the `node.createSubscription = function (msg, cb) {...}` in opcua-iiot-listener.js

would be great if it could be added to the code

**Comment by biancode** [comment]
coming with next release
