### ISSUE TITLE
How to control client subscription publishing interval?

### ISSUE THREAD

**Issue by cristipogacean** [BiancoRoyal/node-red-contrib-iiot-opcua#7]
Hi, 

It seams that Client's subscription publishing interval is defaulted to 10 seconds.  Is there a possibility to be changed to a desired value? Monitored item's sampling rate respective queue size are configurable and  seam to function properly.

Thank you and kind regards,
Cristian

**Comment by biancode** [comment]
Hi,

Yes, sure!

With an inject ...

<img width="521" alt="grafik" src="https://user-images.githubusercontent.com/4369867/36109165-f17d1572-101e-11e8-9772-29ace093feab.png">

**Comment by cristipogacean** [comment]
Hi again,  

I was aware about the inject you mentioned, nevertheless I think, from the behavior I see, the "interval" parameter refers there to the monitored item "sampling rate" and not to the subscription's publishing interval. 

The behavior that I see is that with the above mentioned settings: I get every 10 seconds a package of 10 data-changes (sampled every 500ms). when I change the queue size to 1, then I get a data-change every 10 seconds.

How would you recommend to configure the inject in order to receive data-changes packed in publish responses with a frequency different than 10 seconds? 

Thank you and kind regards,
Cristian

**Comment by biancode** [comment]
![image](https://user-images.githubusercontent.com/4369867/36640806-f62bf8de-1a25-11e8-8f54-5c23cb0280f3.png)

**Comment by biancode** [comment]
![image](https://user-images.githubusercontent.com/4369867/36641385-2e04dc0e-1a2f-11e8-8d2c-8951bc0d7cf2.png)

![image](https://user-images.githubusercontent.com/4369867/36641396-3bc57a10-1a2f-11e8-8261-476a0731358e.png)

The msg.payload could change the requestedPublishingInterval parameter.

**Comment by biancode** [comment]
read the new info of the node and try the new msg.payload.options to test, please
