### ISSUE TITLE
Issue with boolean on result filter

### ISSUE THREAD

**Issue by NichtEuler** [BiancoRoyal/node-red-contrib-iiot-opcua#75]
Hi,

I am currently testing out this wonderful kit.
But I came across some strange issue with the result filter.

Currently I am listening to a boolean value. But when i enable "send just values" even if the node says that it's boolean value is false, the results come back as true.

After disabling "send just values" if the boolean value is true, the value of the node is in msg.payload : "true", but when it is false, the value is in payload.value.value : "false".

Maybe I am not using the filter correctly or this is a bug.

Thank you

**Comment by biancode** [comment]
Hi, 
please use the issue template and reopen! I need more information or an example flow, please. Screenshot from UAExpert would be great about the OPC UA Node properties and value in the different states.
It sounds like a problem with the value or data type while converting boolean. (boolean could also get string and number in some cases)
