### ISSUE TITLE
question - german locale

### ISSUE THREAD

**Issue by jwende** [BiancoRoyal/node-red-contrib-iiot-opcua#78]
Just wondering if you have any plans to translate the html help too ?
Cheers
J.

**Comment by biancode** [comment]
Hello Jörg, 

I'm sorry, there is no plan for now - maybe next year ... first there is a lot of work to go further (1.04 etc.)

Happy wiring!

**Comment by jwende** [comment]
All good .... thanks for your hard work 
J.

**Comment by biancode** [comment]
You are welcome to send me translations and/or better descriptions to add them in the nodes asap.
