### ISSUE TITLE
Source and server timestamp

### ISSUE THREAD

**Issue by NichtEuler** [BiancoRoyal/node-red-contrib-iiot-opcua#80]
**I'm submitting a ...**  (check one with "x")
   
## Problem
 - ( x ) bug report => please search GitHub for a similar issue or PR before submitting

### Information
 **Current behaviour**
 
 Source and servertimestamp not correct
**When setting a value:**
![grafik](https://user-images.githubusercontent.com/33428455/49928640-dffee500-fec0-11e8-919b-b1b240a86db7.png)

**UAExpert:**
![grafik](https://user-images.githubusercontent.com/33428455/49928668-f0af5b00-fec0-11e8-8843-15ac7c162c69.png)

**Time of Node-Red-Container:**
![grafik](https://user-images.githubusercontent.com/33428455/49928743-1ccadc00-fec1-11e8-84d1-384d91ed1433.png)

 **Expected behaviour**
 
 Server and sourcetimestamp correct
 **Minimal reproduction of the problem with instructions**
 

1. Same flow as in #76 
2. Inject

   

#### Your Environment
**Please tell us about your environment:**

  * (x) I have installed https://hub.docker.com/r/nodered/node-red-docker/
        
  * Device :
    - (x) Linux Alpine 

   
   * Description of the connecting OPC UA system:
   
     - Name   : UA-.NETStandard
     - Link   :  https://github.com/OPCFoundation/UA-.NETStandard
     
    
* **node-red-contrib-iiot-opcua version:** ``

* **Node:** (min. 8.x)
   `node --version` = v8.12.0

**Comment by biancode** [comment]
Please, report that issue to node-opcua.
