### ISSUE TITLE
Feature Request Flex Server Node Inject

### ISSUE THREAD

**Issue by Chubacca73** [BiancoRoyal/node-red-contrib-iiot-opcua#85]
Feature

Building a server for different types of machines. For each machine I would like to have a dedicated namespace so:
Machinetype1 --> ns=2
Machinetype2 --> ns=3

The different machine types might have similar variables (for example machine state) wich i would like to give the same node id on both machine types so for example:
Machine State i=1001

Leading to:
Machinetype1 --> ns=2;i=1001
Machinetype2 --> ns=3;i=1001

To my experiance and trials so far the node id and borsw name must be unique per namespace.
As I underdstand the server so far I can only add nodes to ns=1 on the aso server.

Request:
Either give the ability (or descirbe if it is already possible) to add namespaces to the aso server
or
I can crate the namespaces with the flex server and then allow to inject objects into the flex server by selecting the node type and organizaional node.

At the moment I have the feeling that I would have to code the full server object stack inside the Flex server address space tab which to my oppinion is not the node-RED way to do it.

Thanks and best regards!

**Comment by biancode** [comment]
I would prefer the flex server in that case and you'll have all features of [node-opcua](http://node-opcua.github.io/)
