### ISSUE TITLE
Cannot find my OPC UA Server nodes in UaExpert

### ISSUE THREAD

**Issue by PrudhviRajC** [BiancoRoyal/node-red-contrib-iiot-opcua#86]
**I'm submitting a ...** (check one with "x")

### Problem
* (X) bug report => please search github for a similar issue or PR before submitting
* (X) unexpected behavior => please visit the Wiki before

**Current behavior**
I have an XML file (OPC UA Information model) which is extracted from AutomationML editor. I want to import that XML file into node-red, and develop an OPC UA Server.  I have already imported the XML file into node-red, as I can see that the XML file is converted as Node JS objects in debug. 
![node_js_objects](https://user-images.githubusercontent.com/41329370/53007180-0435ef80-3437-11e9-9139-577d3cb29e04.PNG)

I have also added the other XML files because they are dependent on companion specifications (with other namespaceUri's inside my XML model) in the XMLSets of the OPC UA server.
![xmlsets](https://user-images.githubusercontent.com/41329370/53008276-52e48900-3439-11e9-838f-1fa7975487a0.PNG)

I have changed the port to 4840 and successfully established a connection with the Client (UaExpert). But I cannot see any of my nodes from XML file instead there are some other nodes.
![uaexpert](https://user-images.githubusercontent.com/41329370/53007220-19128300-3437-11e9-8fa9-9a1219ceffaf.PNG)

Please refer to the flow, and let me know if the flow and the settings are correct, 
![flow](https://user-images.githubusercontent.com/41329370/53007403-7ad2ed00-3437-11e9-8c59-9cda2a257975.PNG)

**Expected behavior**
 I want to access my OPC UA server nodes using the UaExpert software from Unified Automation.

## Your Environment
**Please tell us about your environment:**

* (X) I am using just the Node-RED package and got node-opcua installed with it
* ( ) I have installed node-opcua global from source (using git clone)
* ( ) I have installed node-opcua as a global package (using npm i -g)
* Device (for Modelling):
  
  * ( ) macOS: v
  * ( ) Linux: Linux 4.15.12-301.fc27.x86_64 #1 SMP x86_64 GNU/Linux
  * (X) Windows: v
  * ( ) Raspbian: v
  * ( ) Other:
    
    * Name:
    * Version:
* Device (for Node-RED execution):
  
  * ( ) macOS: v
  * ( ) Linux: Linux 3.4.113-sun8i #18 SMP PREEMPT armv7l GNU/Linux
  * (X) Windows: v
  * ( ) Raspbian: v
  * ( ) Other:
    
    * Name:
    * Version:
* Description of the connecting OPC UA system:
  
  * Name: node-red-contrib-iiot-opcua
  * Version: 2.7.1
  * Vendor:
  * Link: https://flows.nodered.org/node/node-red-contrib-iiot-opcua
* **node-red-contrib-iiot-opcu version:** 2.7.1
* **Node:** (min. 8.x)
  `node --version` = v10.15.1

**Comment by biancode** [comment]
I'm sorry there is no support for Windows.
