### ISSUE TITLE
Passing falsy payload values to OPCUA-IIoT-Node does not work

### ISSUE THREAD

**Issue by systec-ad** [BiancoRoyal/node-red-contrib-iiot-opcua#88]
## Problem

**bug report**
 
### Information
 **Current behaviour**

1. Passing a *falsy* value (e.g. 0.0) to a OPCUA-IIoT-Node node will result wrong output messages. (NaN, empty strings)
2. The value of messages overrides the *Value* setting
 
 **Expected behaviour**

1. Falsy values should be handled/passed "normal" values
2. The Value should override the message payload as the documentation says. ("It overrides the given payload if it is not null.")
 
 **Minimal reproduction of the problem with instructions**

   1. Inject a falsy value ("" / 0.0 / 0 / false) to a node of type OPCUA-IIoT-Node
   2. Inject a arbitrary value to OPCUA-IIoT-Node, when this node has a valid "Value" setting
   
#### Your Environment

- I have installed node-red-contrib-iiot-opcua
/node-opcua via Node-RED palette manager
- Linux, Debian Stretch (9.6)
- Node-RED version 0.9.15 
- node.js version v10.13.0

## Possible solution

I think the problem is located [here](https://github.com/biancode/node-red-contrib-iiot-opcua/blob/master/src/opcua-iiot-node.js#L60).

Changing the line from

    msg.payload || node.value

to 

    node.value === "" : msg.payload : node.value

should solve the main issue.

Hint: This solution would not allow an empty string as "Value" setting. Not sure if this would be a big issue.

Thanks

**Comment by biancode** [comment]
moved to https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/issues/1
