### ISSUE TITLE
Multitech Conduit Gateway

### ISSUE THREAD

**Issue by Sadafaga** [BiancoRoyal/node-red-contrib-iiot-opcua#91]
Hello,

I have a Multitech Conduit Gateway with node-red installed. Due to the hardware on the Conduit. The maximum nodejs version that Conduit can take is: 0.10.48 and Node Red is: 0.15.3.

And it also does not have C/C++ compiler installed on it due to the hardware limitation.

I would like to know if the first version of "node-red-contrib-iiot-opcua" could be compatible with the nodejs and node-red version of the gateway.

Regards.

**Comment by biancode** [comment]
Hello, I mean node-opcua of IIoT package needs min. NodeJS v6.10+, but give it a try. node-red-contrib-opcua package is much older and it worked with older versions before. Check out the github history of that package!
