### ISSUE TITLE
Method

### ISSUE THREAD

**Issue by abraham200200** [BiancoRoyal/node-red-contrib-iiot-opcua#92]
How can i define a function as a Method of opc ua server with iiot nodes

**Comment by biancode** [comment]
within the flex server

**Comment by Jack-Linda** [comment]
can i find a example of define a function as a Method within flex server

**Comment by biancode** [comment]
@Jack-Linda check out the Import inside Node-RED: Import -> Examples -> iiot opcua

**Comment by Jack-Linda** [comment]
> @Jack-Linda check out the Import inside Node-RED: Import -> Examples -> iiot opcua

I am very sorry I can't find a examples of define a function as a Method of opc ua server by flex server.can I define it in address Space of flex server?how to do it? I'm dying to get your help.

**Comment by biancode** [comment]
@Jack-Linda http://node-opcua.github.io/ you can use the whole node-opcua API - take a bit time to learn more about the API, please!
