### ISSUE TITLE
Node-red-contrib-iiot-opcua | empty field

### ISSUE THREAD

**Issue by Sadafaga** [BiancoRoyal/node-red-contrib-iiot-opcua#93]
**Current behaviour**

I have an OPC UA server running and connected to UA Expert. I have tried to inject data from the general "inject node" to a "OPCUA-IIoT-Server-ASO" and after that to the OPC UA Server, everything is ok except the field "value" that has as value " " instead the string that I am injecting. How can I fix it?

 I hope that this image can help to understand my problem. You can see remarked in red the type of "opc ua node" that I am using and remarked in blue the ouput with the field value with a " " instead of "hello" that is what I am injecting.
 
![flow_opcuaserver](https://user-images.githubusercontent.com/33282160/55941274-2fbca580-5c42-11e9-85ad-b15e9acc7771.png)

 **Expected behaviour**

I expect that in the field "value" it appears the string "hello" and not " ".
    
 
  * Device :   
   
    - (x ) Raspbian: Raspbian GNU/Linux 9 (stretch)   
    
* **Node-RED version:** 
0.20.0

* **Node:** (min. 8.x)
10.5.3

**Comment by abraham200200** [comment]
to write a value you need the write node('OPCUA IIoT Write')

**Comment by Sadafaga** [comment]
my intention is to take the data I receive in mqqt to the server opcua but I recive this " " or the following error message "Error: ASO NodeId Is Not Valid"

**Comment by Sadafaga** [comment]
I'm getting the following error "nodeId ns = 1; s = XXXX already registered" and I would like that every time I inject a message this overwrites the previous one and therefore does not appear this error message. How can I fix it? Thanks
