### ISSUE TITLE
Error permission denied certificates | OPC UA IIoT Flex Server

### ISSUE THREAD

**Issue by Sadafaga** [BiancoRoyal/node-red-contrib-iiot-opcua#94]
### Information
 **Current behaviour**
 The problem is that when I try to deploy a flow I get the problem that you can see in the following screenshot. I don't know how to fix it. Thank you!
 
 **Expected behaviour**
 
I expect that the Flex Server node that I am using works and put itself in "active mode".
 
  
![error_flexserver_opcuaiiot](https://user-images.githubusercontent.com/33282160/56638302-07836c80-666e-11e9-9d2c-f2b2cbdfad4a.png)

**Please tell us about your environment:**

  * (x ) I have installed node-opcua as a global package (using npm i -g) 
  
  * Device :
    
    - ( x) Raspbian: Raspbian GNU/Linux 9 (stretch) 
  
   
   * Description of the connecting OPC UA system:
   
     - Name   :
     - Version:
     - Vendor :
     - Link   : https://
     
* **Node-RED version:** 
0.20.0

* **node-red-contrib-iiot-opcua version:** ``
 Last one

* **Node:** (min. 8.x)
  10.5.3

**Comment by biancode** [comment]
looks like user permission problem in the system - check the user to run node-red with
