### ISSUE TITLE
[UPDATED]: Missing description and value in browse/read node

### ISSUE THREAD

**Issue by chminngi** [BiancoRoyal/node-red-contrib-iiot-opcua#95]
## Problem
 - ( ) bug report => please search GitHub for a similar issue or PR before submitting
 - (x) unexpected behaviour => please visit the Wiki before

### Information
 **Current behaviour**
 After upgrading from 2.7.1 to latest version I miss the **description** and **value** field in browser and read node

 **Expected behaviour**
I expect to get a payload structure with description of a nodeId item.
 
 **Minimal reproduction of the problem with instructions**

   1. injector node
   2. browse node with root nodeId
   3. response node
   

#### Your Environment

     -(x) nodeRED: v0.20.5
     -(x) node: v8.x

   * Device :
    
    - (x) macOS: v10.14.4
    - ( ) Linux: v 
    - ( ) Windows: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:

**Comment by biancode** [comment]
there is new concept since 0.4.x of node-opcua

![image](https://user-images.githubusercontent.com/4369867/70855337-87926700-1ec9-11ea-9463-fe79313caab8.png)

![image](https://user-images.githubusercontent.com/4369867/70855340-91b46580-1ec9-11ea-9d28-0eff20754191.png)
