### ISSUE TITLE
How-To OPC UA Server setup

### ISSUE THREAD

**Issue by freaki2010** [BiancoRoyal/node-red-contrib-iiot-opcua#99]
**I'm submitting a ...**  (check one with "x")
## Support
 - support request => **Please do not submit support requests here**, instead see use [the link to our support page](https://bianco-royal.cloud/supporter/#/content/backer)
 - (x) simple question => please visit the Wiki and Info tab by clicking on the node inside Node-RED before
Where can I find a detailed How-To OPC UA Server setup? Nothing is written under the tab [Server](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/wiki/Server) in the [Wiki](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/wiki) and the details in Node-Red itself don't really help me. I am a trainee of a company and got the task to run an OPC-UA server with Node-Red on the IOT2040. 
Thanks in advance for the help!

**Comment by biancode** [comment]
There is no detailed How-To OPC UA Server setup. If you write one, then let us know and we add it to the Wiki.

**Comment by freaki2010** [comment]
What you own cannot be called a wiki.
I would suggest that you take a look at some other wikis and revise yours.
You can't use your wiki for information purposes.
That's not meant to be bad, it's just a fact. sorry...

**Comment by biancode** [comment]
sure - I never said something else - feel free to contribute instead to diss my work, maybe with that, you will see how much work it is to provide more ...

**Comment by biancode** [comment]
Sure, feel free to make it a better one!

**Comment by biancode** [comment]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/4369867/59041021-1c137100-8878-11e9-92cc-372e689211fd.png">

**Comment by biancode** [comment]
[Wiki Upgrade project ](https://github.com/BiancoRoyal/node-red-contrib-iiot-opcua/projects/6) needs more contributors
